# Generated by Django 4.0.2 on 2023-03-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_customer_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='company',
        ),
    ]
