# Generated by Django 4.0.2 on 2023-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_order_area_order_city_order_fname_order_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.TextField(),
        ),
    ]
