# Generated by Django 4.0.2 on 2023-03-14 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_rename_date_order_ddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='owner_name',
            new_name='showroom_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
    ]
